### ISSUE TITLE
Unable to acquire exclusive lock on crs_action - currently lock held by postgres

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#109]
I sometime get an error running an upload job due to locks being held on tables by PostgreSQL.
An hypothesis is that this is due to autovacuum kicking in during large uploads:
https://github.com/linz/bde-processor-deployment/issues/28#issuecomment-311935715

This ticket is to deal with this problem by finding possible solutions, one being automatically disabling autovacuum during loads, or simply documenting the issue to let users decide what to do about it.

\cc @palmerj

**Comment by strk** [comment]
The problem is likely due to calling `_bde_GetExclusiveLock` before dropping the table in `bde_ApplyLevel0Update` function defined in `sql/02-bde_control_functions.sql`.

I'm not sure the call to getting exclusive locking is placed at the right time, nor that it is really needed.
What is that exclusive lock trying to avoid @palmerj ?

**Comment by strk** [comment]
The code is here: https://github.com/linz/linz_bde_uploader/blob/2.3.0/sql/02-bde_control_functions.sql#L1976

**Comment by palmerj** [comment]
> I'm not sure the call to getting exclusive locking is placed at the right time, nor that it is really needed.
What is that exclusive lock trying to avoid @palmerj ?

This is only required during the level_0 first load of the table data. It was historically designed this way to improve performance for loading millions of row (i.e less WAL work) to remove all existing data then load into a "new" copy of the table within the same transaction. The process that is follow for level_0 load is to:

- Get lock on bde.* table
- Drop bde.* table
- Create an exact copy of the bde.* table in temporary schema
- load the data
- Move back to bde schema

Of course we could remove this performance improvement (~20% from memory), or look for another implementation :)

**Comment by palmerj** [comment]
P.S my view is the best option is to temporarily autovacuum by config modification and reload.

**Comment by strk** [comment]
My question is: why locking the table at all ? What does it prevent ?
Can't you just do the following ?

 * Create new table in temporary schema
 * Load the data in temporary table
 * Drop bde.* table
 * Move new table to bde schema.

**Comment by palmerj** [comment]
It's about getting a lock to be sure we can drop the table. Note the function  that get a the lock tries for at 60 secs before giving up. 

By removing the function call we would have a larger risk not being able to drop the table. But I guess it's not so much of a big deal as it only during the `full` linz_bde_uploader process run which is generally only ever run once on the first import of data into clean database.

**Comment by strk** [comment]
I see, so we basically request a lock for the sole purpose of having
a chance to wait before giving up on our attempt to drop the table.
And we wait up to 60 seconds.

Would it make sense to obtain locks on all tables up-front, before
even starting the first load ?

**Comment by palmerj** [comment]
> Would it make sense to obtain locks on all tables up-front, before
even starting the first load ?

Yes that would make sense to save time if locks can not be obtained. This would require a few additional changes to implement.

**Comment by strk** [comment]
as I'm waiting for "simplified layers maintainance" functions running in a separate transaction to finish before my simple query against a BDE table returns, I'm not wondering we we could avoid the lock completely. Why do we need to *drop* the old table instead of TRUNCATE it and writing new data into it ? (did not test if TRUNCATE locks the table, but I don't see why it shoud)

**Comment by palmerj** [comment]
Sorry I never replied to @strk.

> Why do we need to drop the old table

Maybe we don't if truncating the table also allows provides the same level_0 first loading performance.

**Comment by strk** [comment]
I'm going to run performance tests to see what does dropping the lock implies

**Comment by strk** [comment]
Running the tests I stumbled upon bugs:
https://github.com/linz/linz-bde-uploader/pull/194
https://github.com/linz/linz-bde-uploader/pull/193
Please review/approve

**Comment by strk** [comment]
I've run a test comparing TRUNCATE/COPY vs. ALTER TABLE SET SCHEMA (current).
The current implementation is clearly faster.

Current:
```
2019/04/11 16:22:17 Counting current and new version of table
2019/04/11 16:22:50 Dropping current version of the table crs_adj_obs_change
2019/04/11 16:22:50 Renaming the new version to replace the current version
2019/04/11 16:22:50 Restoring dependent objects
2019/04/11 16:22:50 Recording the upload
2019/04/11 16:22:50 Table crs_adj_obs_change completed: 88384369 insertions, 0 updates, 88384369 deletions
2019/04/11 16:22:50 Job 22 finished successfully
2019/04/11 16:22:50 Duration of job: 00:08:15
```

With TRUNCATE:
```
2019/04/11 18:09:18 Counting current and new version of table
2019/04/11 18:09:37 Truncating table crs_adj_obs_change
2019/04/11 18:09:37 Copying new data to crs_adj_obs_change
2019/04/11 18:19:10 Recording the upload
2019/04/11 18:19:10 Table crs_adj_obs_change completed: 88384369 insertions, 0 updates, 88384369 deletions
2019/04/11 18:19:11 Job 25 finished successfully
2019/04/11 18:19:11 Duration of job: 00:17:43
```

**Comment by strk** [comment]
Of course the above implementation for TRUNCATE is naive in that it basically copies the data twice instead of directly loading into the target table. That one is still to be tested...

**Comment by strk** [comment]
BTW, looking at the code I saw that upon first load the uploader _unversions_ the target table if it is versioned. I suspect it assumes that full loads are always followed by enabling of versioning, which isn't necessarely true

**Comment by palmerj** [comment]
Closing and see if PG 10 produces this again
