### ISSUE TITLE
Multiple LoL versions compatibility support

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-uploader#136]
Implement support for processing BDE files from multiple LoL versions in one `linz_bde_uploader` version. This mean that `linz_bde_uploader` could change it's configuration depending on LoL version information found in BDE file.

This would allow us to implement support for upcoming new LoL version upfront and `linz_bde_uploader` will switch to that version when new BDE data will arrive. Currently this is done by deploying new `linz_bde_uploader` just shortly before the time when new BDE data is supposed to arrive, which can cause incorrect data processing in case of  something goes wrong.

**Comment by imincik** [comment]
@billgeo , can we somehow detect LoL version from BDE files ?

**Comment by billgeo** [comment]
I've asked LOL team to consider adding a version to the header as a future enhancement. But that would only help with new BDE files. 

For old BDE files we only have the date that it was created.

**Comment by imincik** [comment]
Thanks @billgeo . This is enough information for now.

**Comment by palmerj** [comment]
> So I don't think we need to necessarily process old BDE files (although that could be a useful feature)

Processing process old BDE files is a completely new project and has many other decisions around it. I would limit the current discussion to processing and testing production and development versions of BDE files.

**Comment by billgeo** [comment]
Just a note, that we could possibly write a script to insert the LOL version into old BDE file headers if there is a record somewhere of dates that LOL versions were released. Would need complete record back to the oldest BDE file we have.

**Comment by palmerj** [comment]
@imincik to review. I think this issue might never get implemented. We now have headers in the BDE files to at least abort the BDE Processor run if the version doesn't match.

**Comment by imincik** [comment]
I still think this feature needs to be developed. I will keep it.
