### ISSUE TITLE
[debian] Drop dependency on PostgreSQL package

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#141]
You don't need a PostgreSQL package installed on the system in order to use linz-bde-uploader.
The database could be remote, so we only need the libpq client here (indirectly, via perl).

Right now PostgreSQL package is required both directly and indirectly via other dependencies like postgresql-tableversion. Those dependencies should also be dropped as they are really only dependencies for the target database.

Things may change now that we have the schema-loader script, for that one, we do need parts of tableversion, specifically the non-extension side of it, but at the moment tableversion package is a single one so we cannot distinguish between the two.

For the sake of this ticket, it's enough to drop the _explicit_ (direct) dependency on PostgreSQL server, the rest will be dealt with by separate tickets to the relevant packages.

**Comment by imincik** [comment]
I confirm that we should drop PostgreSQL as dependency. Thanks @strk

**Comment by palmerj** [comment]
This should stay open and the server dependencies should be dropped

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
Relevant

**Comment by strk** [comment]
For the record, table-version still needs to be a requirement because our schema loader will invoke table_version-loader, which is provided by those packages. Things may be improved by splitting table-version into separate packages (one agnostic from database) as requested in https://github.com/linz/postgresql-tableversion/issues/95

**Comment by strk** [comment]
I'm reopening this as it won't really be solved until dependent packages aren't fixed.
It may boil down to dealing with https://github.com/linz/postgresql-tableversion/issues/95 which I'm going to do next.

**Comment by strk** [comment]
Once https://github.com/linz/postgresql-tableversion/pull/203 is merged and new packages are published, this issue will be about changing the requirement from `postgresql-xx-tableversion` to just `tableversion`
