### ISSUE TITLE
Review usage of security-invoker table_version.ver_delete_revision

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#151]
Such usage may suffer from provilege issues because it's not SECURITY definer while it tries to delete rows from a table in the `table_version` schema. See https://github.com/linz/linz-bde-schema/issues/70

\cc @palmerj

**Comment by strk** [comment]
The function seems to be actually documented:
https://github.com/linz/postgresql-tableversion/blob/1.4.0/doc/table_version.md#ver_delete_revision

The fact that it is not a security-definer may still be an issue, needs to be checked.

**Comment by strk** [comment]
As of `table_version` 1.7.0, any user can create a revision, using `ver_create_revision` (it being a `SECURITY DEFINER`) but only someone with direct write access in `table_version` tables can delete revisions using `ver_delete_revision`, which is `SECURITY INVOKER`). While it makes sense not to grant permissions to anyone to remove a revision, I wonder if the _responsible_ for a revision should be made capable of deleting it (when a revision is created, it is done so in the name of a database user, which could be checked against for removal). This sounds like being a ticket to file upstream anyway, so here it is: https://github.com/linz/postgresql-tableversion/issues/178

**Comment by palmerj** [comment]
Maybe it's ok to allow the creator of the revision to delete it as well.

**Comment by strk** [comment]
Only an empty revision can be deleted, anway, right ?

**Comment by strk** [comment]
I've implemented grant-to-delete-by-creator in https://github.com/linz/postgresql-tableversion/pull/181 - please review

**Comment by strk** [comment]
I'm closing this after https://github.com/linz/postgresql-tableversion/pull/181 was merged. It should be fine that we try to delete an empty revision.

I'm assuming it's not possible to modify any versioned table from a different transaction, which may be a wrong assumption, but it's something to handle at the `table_version` level anyway..
