### ISSUE TITLE
-override does not remove the stale lock

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#169]
I noticed that passing -override to linz_bde_uploader does NOT remove an existing 'A' (active) record in bde_control tables, while it ignores it. I think it should also remove it.

This is to be confirmed/verified.

**Comment by palmerj** [comment]
I agree with this change

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
still relevant as an improvement to write

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
I'm not sure we should make this change as there's an explicit `-remove-zombie` switch as well, which should do the cleanup. Should we make `-remove-zombie` implied when `-override-locks` is given ?

**Comment by strk** [comment]
After discussion in meeting, I'm closing this for the above reason
