### ISSUE TITLE
Rename repository to linz-bde-uploader

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#171]
I'm tired of hitting the SHIFT key. Aren't you, @imincik ?

**Comment by strk** [comment]
Initially, all references should work, because I think github keeps redirects.
I suggest you rename and we'll take care of all issues as we find them

**Comment by imincik** [comment]
I renamed repo just now. Would you please check source code, I will approve quickly all PRs. Thank you.

**Comment by strk** [comment]
Repo renamed, all fine here. Let's postpone debian package rename (if we'll ever want to do that) and executable rename...
