### ISSUE TITLE
[schema-loader] Bogus handling of schema loader return codes

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#178]
Schema loader is currently using:

      `backtick` || die

for handling errors from spawned commands, but that syntax is bogus in that it dies if the invoked command doesn't return any output. This is the case with new schema loaders supporting `stdout` as they would only print progress to stderr when NOT asked to print output to `stdout`.

We'd better use `system()` instead.

Note this bug is NOT present in current master branch, to become 2.5.0, in that the schema loader was rewrote to support `stdout` and transactionality, so this bug ONLY affect releases up to 2.4.0.

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
2.5.0 was released with this bug fixed so we can close this
