### ISSUE TITLE
Publish packages for Xenial

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#190]
Apt packages for Xenial (Ubuntu 16.04) are needed if we want to start testing PostgreSQL-11, because PostGIS is NOT available for PostgreSQL-11 in Trusty (Ubuntu 14.04)

**Comment by imincik** [comment]
As we discussed during yesterday's meeting, we are not publishing non Trusty packages for now.

**Comment by strk** [comment]
@imincik were we saying today it could be time to move this Epic on?

**Comment by imincik** [comment]
We should migrate to Ubuntu 18.04. 16 doesn't make a sense anymore.

**Comment by strk** [comment]
so closing this. in favor of #207
