### ISSUE TITLE
Publish updated packages accepting tableversion/dbpatch for PostgreSQL 10/11

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#192]
After merging #191 we need new packages published to accept tableversion for PostgreSQL-10 and 11, do we need a new tagged release for that ? Because the only change so far has been in debian packages...

**Comment by imincik** [comment]
If no change is outside of `debian` dir, no tag from you @strk is needed.

**Comment by strk** [comment]
the master branch does have changes, does it make sense for me to backport the debian-only changes to the release-2.5 branch to cut a new debian package ?

**Comment by imincik** [comment]
I am just backporting `debian/control` changes. Is there anything else ?

**Comment by strk** [comment]
nope, that's enough

**Comment by imincik** [comment]
Package uploaded to `test`

**Comment by strk** [comment]
thanks
