### ISSUE TITLE
Publish packages for Bionic

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#207]
Apt packages for Bionic (Ubuntu 18.04) are needed if we want to start testing PostgreSQL-11, because PostGIS is NOT available for PostgreSQL-11 in Trusty (Ubuntu 14.04)

Replaces #190

**Comment by imincik** [comment]
This task is still relevant.

**Comment by strk** [comment]
relevant

**Comment by strk** [comment]
I've pushed a `linz-bde-uploader_2.5.2-1linz~bionic1_all.deb` package to test repository on packagecloud:
https://packagecloud.io/linz/test/packages/ubuntu/bionic/linz-bde-uploader_2.5.2-1linz~bionic1_all.deb

Not sure how to test how good it is...

**Comment by palmerj** [comment]
> I've pushed a linz-bde-uploader_2.5.2-1linz~bionic1_all.deb package to test repository on packagecloud:

Hi @strk where is the PR for this new packaging?

**Comment by strk** [comment]
There is no PR, packaging is done outside of git history

**Comment by palmerj** [comment]
Was just wondering how TravisCI might have gone...

**Comment by strk** [comment]
TravisCI will be testing packages from other repos, see for example https://github.com/linz/linz-lds-bde-schema/issues/141 (and ultimately bde-processor-deployment)

**Comment by strk** [comment]
Reopening until we promote to production

**Comment by strk** [comment]
> Was just wondering how TravisCI might have gone...

You can see travis in action in https://github.com/linz/bde-processor-deployment/pull/606

**Comment by strk** [comment]
For the record: 2.7.0 is now tagged, it would be worth publishing _new_ packages

**Comment by imincik** [comment]
@strk , we are promoting packages from `test` repo branch to `prod` after BDE Processor UAT is done (https://github.com/linz/bde-processor-deployment/wiki/Production-Deployment#production-deployment). I think we don't need this ticket. Will close it.
