### ISSUE TITLE
bde_control.upload.end_time should be NULL for active jobs

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#215]
I noticed that the `end_time` column for records in `bde_control.upload` having status `A` (Active) have a non-null value (the same value as `start_time`). I don't think this makes sense as the `end_time` is effectively unknown until the job really ends...

\cc @palmerj

**Comment by palmerj** [comment]
If that's occuring, then I agree that should be the case. But we will need to review that is the current implementation. This code was now written so long ago...

**Comment by strk** [comment]
It was spotted in https://github.com/linz/ds-dev-team/issues/497#issuecomment-516778798

**Comment by strk** [comment]
According to [schema comment](https://github.com/linz/linz-bde-uploader/blob/2.5.2/sql/01-bde_control_tables.sql#L56), `end_time`  is supposed to be:

> periodically updated during the running of the job and will be used to determine if the job is still active

Such "periodic update" seems to be performed by `bde_control._bde_RefreshLock`, which is called by:

  - bde_control.bde_StartDataset
  - bde_control.bde_BeginUploadTable
  - bde_control.bde_ApplyLevel5Update
  - bde_control.bde_ApplyLevel0Update

So, yes, it's by design that it is NOT set to NULL. Not sure if checking for `end_time` moving is a good way to see if the process is really active, though (maybe there could be a backend pid or something written somewhere, for active records) but that's a bigger change

**Comment by palmerj** [comment]
Ok well this seems to need larger rewrite to be changed then.

**Comment by strk** [comment]
Won't do
