### ISSUE TITLE
WARN> BdeDatabase.pm:756 - SET LOCAL can only be used in transaction blocks

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#219]
We always get this WARNING on every uploader run:
> WARN> BdeDatabase.pm:756 - SET LOCAL can only be used in transaction blocks

It's probably due to this line in configuration file:
```
db_connect_sql <<EOT
SET client_encoding to UTF8;
SET role bde_dba;
SET search_path to {db_schema}, {bde_schema}, public;
set DateStyle= ISO,MDY;
SET LOCAL synchronous_commit TO OFF;
EOT
```

We should fix it

**Comment by strk** [comment]
Why would we want the LOCAL keyword there ? Don't we want to do that for the whole upload session ?

**Comment by palmerj** [comment]
No we don't want the LOCAL keyword here. But I also wonder about the need for the parameter change anyway. My feeling is synchronous_commit  is only going to improve performance for lots of small transactions, not one big long one. maybe remove this line all together.

**Comment by strk** [comment]
Agreed, I'll drop it
