### ISSUE TITLE
More duplicated lines in logs

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#220]
Calling uploader with `-verbose` and `-log-level INFO` seems to result in duplicated output lines again:

```
linz_bde_uploader: 2019/08/28 00:10:18 INFO> BdeUpload.pm:988 - Applying level 5 update 20190827234600 into table crs_feature_name
...
linz_bde_uploader: 2019/08/28 00:10:25 INFO> BdeUpload.pm:1017 - Loading file gnet from dataset 20190827234600
linz_bde_uploader: 2019/08/28 00:10:18 Applying level 5 update 20190827234600 into table crs_feature_name
```

It looks like #59 did not fix all occurrences of this, has to be re-checked.

**Comment by strk** [comment]
@palmerj I tried adding a testcase for this but it does look like this was already fully fixed by #59

**Comment by palmerj** [comment]
So is the code not deployed then?

**Comment by strk** [comment]
2.6.0 is not even tagged/released, that'd be the first step, then it'll need to be packaged and then deployed.

**Comment by palmerj** [comment]
Ah ok great news then.
