### ISSUE TITLE
Run table changes analysis on level 5 updates as well

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#221]
The table changes warnings/errors configured in tables.conf are only raised with level_0 updates, but never with level_5 ones. This ticket is to run those checks for level_5 as well.

It will probably require refactoring bde_control.bde_CheckTableCount function to use appropriate temporary tables for level_5

\cc @palmerj

**Comment by strk** [comment]
Jeremy do you want this to be in 2.6.0 ? Do you plan to work on this or should I ?
We could do this check in `bde_control._bde_RecordDatasetLoaded` which already gets the counts of rows inserted/deleted/updated ...

**Comment by palmerj** [comment]
Can you please work on this.

**Comment by strk** [comment]
If I read the code correctly we only check for the number of deletions. Given we already have this number, for stats, we don't really need to count the actual rows again, as currently done by the `bde_CheckTableCount`, so updating that function is a good idea.

I'm trying to figure how to write a test for this, then will proceed.

**Comment by strk** [comment]
Ok, in #224 I've added a test for warnings and errors due to the table tolerance.
Now, according to [docs](https://github.com/linz/linz-bde-uploader/blob/2.5.2/conf/tables.conf#L41-L44) the configuration for those tolerances are for `level0` updates. In the default configuration those values are requesting an error if rows after a level0 update are `<20%` of rows before the update and a warning if those rows are `<95%`.

Are we sure those values are also good for level5 updates ? BTW, aren't level0 updates supposed to do nothing, since we got there incrementally in chunks via level5 updates ? (I might have misunderstood this part)

**Comment by palmerj** [comment]
> Are we sure those values are also good for level5 updates ?

Yes I think we can work to those levels for level 5 too. I'm thinking however if we want a commandline switch to override the error so we can still apply a change if we think the error really is valid

> BTW, aren't level0 updates supposed to do nothing, since we got there incrementally in chunks via level5 updates ?

level_0 can bring changes if level_5 incremental is not working correctly (putting UTF8 bugs aside!). As noted in the past this doesn't happen very often.

**Comment by strk** [comment]
Ok, level5 checks for excessive drops is ready for review in https://github.com/linz/linz-bde-uploader/pull/228 (includes tests)

**Comment by strk** [comment]
NOTE: refactoring wasn't needed because the checker compares pg_class.reltuples (statistic) with actual count, after the update. A possible improvement would be for the checker function to optionally receive an already computed changeset view (number of inserts/deletes) which is often available, so to avoid a full sequencial scan on the table, but maybe that's worth a separate ticket.

**Comment by palmerj** [comment]
Hmm I remember none of this implementation!

Is it guaranteed that table statistics are updated before job upload, and hence the table row counts from statistics match the actual pre-date row counts? I guess it's working before the CI tests you created are passing.

**Comment by strk** [comment]
For the record: refactoring is done in #230
