### ISSUE TITLE
Use default values for level5_starttime_warn_tolerance and level5_starttime_fail_tolerance

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#225]
Those two configuration variables have no defaults, so the loader bails out when unset.
This would be a continuation of #78

**Comment by palmerj** [comment]
Looks like good defaults are error= 0.20, warning=0.95

**Comment by strk** [comment]
The default configuration has these values:
```
conf/linz_bde_uploader.conf:134:level5_starttime_warn_tolerance 0.5
conf/linz_bde_uploader.conf:135:level5_starttime_fail_tolerance 0
```

**Comment by palmerj** [comment]
Ops sorry I'm now confused with the table.conf parameters! 

So what was the questions for me?

**Comment by strk** [comment]
How about using 0 as a default, that would be _disable_ the defaults ?

The question was: what values to use as code-defaults (when not written in configuration) for `level5_starttime_warn_tolerance` and `level5_starttime_fail_tolerance` ? (I'd use 0 for both...)

**Comment by strk** [comment]
I've added defaults (0) as part of https://github.com/linz/linz-bde-uploader/pull/228
