### ISSUE TITLE
Fifth parameter to LINZ::BdeUpload::LoadFile has undefined default value ?

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#226]
While writing tests I received errors coming from the BdeUpload::CheckStartDate function, which is ONLY called by BdeUpload::LoadFile WHEN the `checktime` (5th) parameter evaluates to true.

Now, it looks to me that no `LoadFile` caller ever passes more than 4 parameters, so the 5th should always be undefined.

This issue is to understand if we're using undefined behaviour with the LoadFile code or not, because I don't think my test code is doing anything different than before but looks like ending up passing a true value to LoadFile...

\cc @palmerj

**Comment by strk** [comment]
Ok, figured. It's the 4th, not 5th, parameter (first one is "self"). So this is called from `UploadTable`, and the parameter value is determined by last upload stats in database.

**Comment by palmerj** [comment]
Yes correct!
