### ISSUE TITLE
Package version 2.8.1 with dropped PostgreSQL dependency

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-uploader#258]
Package new version with dropped PostgreSQL dependency.

**Comment by strk** [comment]
I guess it should be something like `2.8.0-2linz_bionic1` ? Or would it be `2.8.0-1linz_bionic2` ? I'm not sure what that `1` represent in each side of `linz_bionic` ...

Note I updated the issue title to be clear about what it means.

**Comment by strk** [comment]
Ok I did merge a change, so we can make this 2.8.1 if you want

**Comment by imincik** [comment]
@strk , I released 2.8.1 now.
