### ISSUE TITLE
Package version 2.8.0 with dependencies fixed

### ISSUE THREAD

**Issue by imincik** [linz/linz-bde-uploader#262]
Package new version containing `tableversion` dependency fix.

**Comment by strk** [comment]
Could you please include more info about the dependency problem ? Or (better) a link to a ticket in which such problem is described ?

**Comment by imincik** [comment]
@strk , see: https://github.com/linz/linz-bde-uploader/pull/261

**Comment by imincik** [comment]
Package https://packagecloud.io/linz/test/packages/ubuntu/bionic/linz-bde-uploader_2.8.1-2linz~bionic1_all.deb uploaded to `test`.
