### ISSUE TITLE
Dependencies installation problem

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#264]
According to github-action, both `tableversion_1.8.0-2linz~bionic1_all.deb` and `postgresql-10-tableversion 1.8.0-2linz~bionic1` packages ship a `/usr/bin/table_version-loader` file,
see https://github.com/linz/linz-bde-uploader/pull/263/checks?check_run_id=566837215#step:3:635

This should NOT be the case, with latest code in `tableversion`, in that _ONLY_ the postgresq-agnostic package should contain that file.

We have to find out how the package were created (from which tag/git-hash) and whether there's something to fix upstream.

\cc @imincik

**Comment by imincik** [comment]
postgresql-10-tableversion contains `/usr/bin/table_version-loader` as well.

see: https://packagecloud.io/linz/test/packages/ubuntu/bionic/postgresql-10-tableversion_1.8.0-2linz~bionic1_all.deb?page=2

**Comment by strk** [comment]
I've opened a PR to add CI testing for both deb packages install of tableversion: https://github.com/linz/postgresql-tableversion/pull/215

**Comment by imincik** [comment]
Even if we have loader script only in agnostic version I don't think you should recommend to have non-agnostic and agnostic packages installed in parallel.

**Comment by strk** [comment]
non-agnostic is recommended because you need them if you want to use the loader withouth the --no-extension switch.

I confirm table-version packages created with `make deb` from the `debian/1.8.0-2linz_bionic1` tag do not have the problem of duplicated loader:

strk@liz:/usr/src/linz/postgresql-tableversion/postgresql-tableversion((HEAD detached at debian/1.8.0-2linz_bionic1))] for pkg in ../*.deb; do echo "[`basename $pkg`]"; dpkg -c $pkg  | grep loader; done
[postgresql-10-tableversion_1.8.0-2linz~bionic1_all.deb]
[tableversion_1.8.0-2linz~bionic1_all.deb]
-rwxr-xr-x root/root      2356 2020-04-02 17:43 ./usr/bin/table_version-loader
```

So it looks like packages published on packagecloud where built in some different way ? Possible ?

**Comment by imincik** [comment]
For me `make deb` creates packages with loader script in all packages.

And yes, packages for Packagecloud are not built using `make deb`. It is more complex there.

**Comment by strk** [comment]
Could you please then file a ticket on `postgresql-tableversion` repository to tackle this problem of yours ? Note I was on the debian tag, not on "master" as you seem to be

**Comment by strk** [comment]
I just run `make deb` in master branch and I have the same behaviour: loader only in agnostic package. But I see you have multiple PostgreSQL pacakges, so maybe the bug is there, in that I only remove the loader from the _latest_ release package, rather than from all of them ! Surely worth a ticket on tableversion. Let me know if you want me to create it, meanwhile I'll work on fixing it

**Comment by strk** [comment]
> For me `make deb` creates packages with loader script in all packages.

Not really, see how `[postgresql-11-tableversion_1.8.0-2linz~bionic1_all.deb]` does not include it.
The LATEST version supported does not include it. Instead we want NONE of those to include it.
It'll be fixed with merging https://github.com/linz/postgresql-tableversion/pull/215 (when Microsoft machines get out of trouble)

**Comment by strk** [comment]
And for dbpatch I have https://github.com/linz/postgresql-dbpatch/pull/63 waiting for review.
