### ISSUE TITLE
schema loader: avoid ALTER TABLE when not needed

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#265]
Running `ALTER TABLE` requires AccessExclusiveLock on the target table, this would be better avoided if not needed, to reduce the odds of deadlocks.

In particular `ALTER TABLE bde_uploader.xxxx OWNER TO bde_dba` may be avoided if `bde_dba` is already owner of the table.

**Comment by imincik** [comment]
Should be closed by https://github.com/linz/linz-bde-uploader/pull/266
