### ISSUE TITLE
Remove updates for Statist Areas from the BDE

### ISSUE THREAD

**Issue by billgeo** [linz/linz-bde-uploader#39]
Statist Areas are now all but deprecated and LOL is not the official source for this information.
- [ ] check who is using this and move to alternative source
- [ ] remove from updates for BDE processor (should leave the table there for historic purposes)

**Comment by palmerj** [comment]
Moved to https://github.com/linz/linz-bde-schema/issues/23

**Comment by strk** [comment]
The table is referenced by these files:
```
conf/linz_bde_uploader.conf:267:    crs_statist_area
conf/tables.conf:191:TABLE   crs_statist_area             key=id          row_tol=0.20,0.95   files stt3
```

That's the default configuration, tells ti include the table in the upload, and describes which BDE file contains the update. Shall we drop those lines from those 2 files ?

**Comment by palmerj** [comment]
I would suggest just commenting the lines out for now. If we do that we can at least see that it was once in the configuration.

**Comment by strk** [comment]
I see in other cases a comment was added but the line was not commented out, like this:

> TABLE   crs_road_name_asc            key=audit_id    row_tol=0.20,0.95   files rns # no longer unloaded from 8/12/2016

is this supposedly another such case of "no longer unloaded" ? If so, do we have a date ?

**Comment by palmerj** [comment]
> is this supposedly another such case of "no longer unloaded" ? If so, do we have a date ?

I understand it is no longer uploaded, but @billgeo can confirm

**Comment by strk** [comment]
@billgeo please check if #144 sounds ok.
The outcome of that should be that the *default* configuration for linz-bde-uploader would be to NOT upload the crs_statist_area anymore (note that this would mean possibly ending up with an *empty* such table in the database)

**Comment by billgeo** [comment]
@strk 

> The outcome of that should be that the default configuration for linz-bde-uploader would be to NOT upload the crs_statist_area anymore

yes, that sounds okay

> is this supposedly another such case of "no longer unloaded" ? If so, do we have a date ?

I have emailed the property rights team to confirm this.
