### ISSUE TITLE
Implement/Update tests

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#61]
Provide automated tests, and have `make check` run them

**Comment by strk** [comment]
TODO:
 -  [ ] Test more missing configuration items (up to minimal)
 -  [ ] Test all commandline switches
 -  [ ] Test uploading files

**Comment by strk** [comment]
Only thing left here is to test all commandline switches.
Here's the full list:
- [ ] -config-path or -c cfgpath                                                
- [ ] -config-extension or -x cfgext                                            
- [ ] -purge or -p                                                              
- [ ] -remove-zombie or -z                                                      
- [ ] -full or -f                                                               
- [ ] -full-incremental or -j                                                   
- [ ] -incremental or -i                                                        
- [ ] -rebuild or -r                                                            
- [ ] -before or -b yyyymmdd                                                    
- [ ] -maintain-database or -m                                                  
- [ ] -dry-run or -d                                                            
- [ ] -full-timeout or -t timeout                                               
- [ ] -inc-timeout or -u timeout                                                
- [ ] -override-locks or -o                                                     
- [ ] -skip-postupload-tasks                                                    
- [ ] -listing_file or -l listing_file                                          
- [ ] -keep-files or -k                                                         
- [ ] -version                                                                  
- [ ] -verbose or -v                                                            
- [ ] -log-level                                                                
- [ ] -enable-hooks or -e                                                       
- [ ] -help or -h

**Comment by palmerj** [comment]
Any reason why this never got finished?

**Comment by strk** [comment]
changes in priorities
