### ISSUE TITLE
require_all_dataset_files directive is not documented

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#88]
While working on adding defaults I found a `require_all_dataset_files` directive being required (lacking a default) but not documented. Neither README nor POD documentation says what it is for.

What is its semantic ?

**Comment by strk** [comment]
NOTE: even if I set it to 0, the lack of a dataset file results in a run error:
```
Failed to load level 0 update for test_table from 20170622170629
```

**Comment by strk** [comment]
Complete error:
```
Failed to load level 0 update for test_table from 20170622170629: 
The files test_file required to update test_table are not available in dataset 20170622170629 
at /usr/src/linz/linz_bde_uploader/blib/script/../lib/LINZ/BdeUpload.pm line 904
```

**Comment by palmerj** [comment]
The config is documenting what the option does: https://github.com/linz/linz_bde_uploader/blob/97259d71565c0f53bfd18c8a8e0c2b1af2349576/conf/linz_bde_uploader.conf#L137

Is it working as expected?

**Comment by strk** [comment]
According to https://github.com/linz/linz_bde_uploader/issues/88#issuecomment-310415507 it is not
