### ISSUE TITLE
Process interruption leaves database in inconsistent state

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#96]
When killing `linz_bde_uploader` the database tables are left untouched so that on next run the script will complain that "another processor is in progress".

This ticket is to use a signal handler to cleanup the database.
A separate ticket would be needed to make the "lock" smarter.

**Comment by palmerj** [comment]
Hi @strk I agree a smarter lock management approach could help as we have had this problem in the past. I came up wiith a solution using the bde-processor wrapper script that is called by from. See here https://github.com/linz/bde-processor-deployment/blob/master/deployment/roles/bde-processor/files/scripts/bde_upload#L78. This wrapper uses the -remove-zombie option  (https://github.com/linz/linz_bde_uploader/blob/master/bin/linz_bde_uploader.pl#L233) which clears the upload job table status. If this solution is not enough and you see a good reason to fix it in the linz_bde_uploader script then please do. 

Note one issue with using a PID check is the script can be executed from a remote host. So any so any solution needs to account for that.

**Comment by strk** [comment]
`-remove-zombie` and `-override-locks` are good enough for me at the moment, anyway the idea of storing the PID of the running process also works for remote execution because the PostgreSQL backend PID will still be local. The only thing that would break if we take that approach is when the *same* database connection is used by multiple things, so a process would still look like active while instead it would just be kept alive by a pgsql pooler.

Anyway this ticket is not about making the lock smarter. Ticket #97 is.

This ticket is instead about placing a signal handler in the `linz_bde_uploader` script itself to call BdeUpload::FinishJob if a job was ever started. This is already done in a [finally](https://github.com/linz/linz_bde_uploader/blob/master/lib/LINZ/BdeUpload.pm#L599-L605) block but that block is not invoked on SIGINT.

It could still fail to cleanup the locks (ie: database crash or database connection destroyed).

**Comment by palmerj** [comment]
Sorry please transfer any relevant comments from here into #97.

**Comment by palmerj** [comment]
Yes good idea to improve the signal handler to clean up cancelled jobs from sigint

**Comment by strk** [comment]
The idea of cleaning up on sigint seems still good to me.

**Comment by palmerj** [comment]
Ok thanks. StaleBot Ignore label added
