### ISSUE TITLE
Cannot create upload job - another job is already active

### ISSUE THREAD

**Issue by strk** [linz/linz-bde-uploader#97]
The presence of a record in  `bde_control.upload` having `state` value of `A` (Active) results in this error being printed upon running a new uploader job:
```
Cannot create upload job - another job is already active
```

But no such job is really in progress.

As the uploader script creates persistent connections to the backend, we could maybe store the PID of the backend running the job and checking for it to be still connected before giving the message. If the backend is gone, the job should be marked as completed on error (or "interrupted").

See #96 for a way to produce such inconsistent state.

**Comment by strk** [comment]
I just found that `-remove-zombie` switch is meant to do the cleanup of "active" jobs, but it is based on timeout rather than on existence of backend PID. Maybe the message might include a suggestion to pass `-remove-zombie` if the user thinks it's a stale record ?

**Comment by strk** [comment]
And `-override-locks` switchs forces override no matter expiration...

**Comment by palmerj** [comment]
@strk `-remove-zombie` option looks for jobs that are recorded as active but are no longer running then will release the locks, delete working directories/temp schemas, and set the job status to error

**Comment by strk** [comment]
@palmerj how does `-remove-zombie` determine `no longer running` ? Is it not just based on timeout ? I see it calls `releaseExpiredLocks` [here](https://github.com/linz/linz_bde_uploader/blob/master/lib/LINZ/BdeUpload.pm#L509)

**Comment by palmerj** [comment]
A better error message would be good. Note the remove zombie jobs has no timeout, it just tries to delete jobs if it can. E.g no database lock present

**Comment by strk** [comment]
I see. Any reason not to try that always ? Is it dangerous to rely on those database locks to tell if a job is still active or not ? Or is it because of the filesystem cleanup that we don't want to do it automatically ?

For improved error message see how you like #98 please (not much, but I didn't feel like hinting for commandline switches from within a library which does not handle the commandline switch itself...)

**Comment by palmerj** [comment]
Ah last todo email on my list!

> I see. Any reason not to try that always ? Is it dangerous to rely on those database locks to tell if a job is still active or not ? Or is it because of the filesystem cleanup that we don't want to do it automatically ?

I just reviewed [bde_ReleaseExpiredLocks](https://github.com/linz/linz_bde_uploader/blob/master/sql/02-bde_control_functions.sql#L168) and it seems I was wrong, there are no real database locks checked to determine if a upload is still active. See the implementation for [_bde_LockIsCurrent](https://github.com/linz/linz_bde_uploader/blob/master/sql/02-bde_control_functions.sql#L418) which is only doing a time based expiry check. So maybe that implementation of linz_bde_uploader could be fixed to use some real check to see if the job is still running. Of course this is moot point if we always run the linz_bde_uploader via the wrapper bde_upload script which checks if the process is still running.

**Comment by palmerj** [comment]
Can this now be resolved with the NG BDE Processor wrapper script?
